### ISSUE TITLE
error parse when have semicolon at last

### ISSUE THREAD

**Issue by magicode** [jshttp/content-disposition#11]
```js

var contentDisposition = require('content-disposition');

//error
contentDisposition.parse('attachment; filename="file.zip";');

//no error
contentDisposition.parse('attachment; filename="file.zip"');

/*
node_modules/content-disposition/index.js:369
    throw new TypeError('invalid parameter format')
    ^

TypeError: invalid parameter format
    at Function.parse (node_modules/content-disposition/index.js:369:11)
    at Object.<anonymous> (content-disposition.js:3:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:575:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
*/

```

**Comment by dougwilson** [comment]
Correct, because that is not a valid header string, as specified by RFC 6266: https://tools.ietf.org/html/rfc6266

**Comment by magicode** [comment]
But not all websites conform to RFC 6266, such as https://www.fotolia.com
It is possible they do this purposely in order to disable scripts.
Perhaps it makes sense to add an option of "loose" parsing, for websites that don't follow the standards.‏

**Comment by dougwilson** [comment]
Hi @magicode, you're certainly welcome to make a pull request to implement a "lax" mode of parsing! If we are not parsing according to the standard, we may want to lay out exactly what the parsing algorithm would be. Can you do that as well? Perhaps it can build off of pre-existing algorithms, like some web browsers (assuming they are not crazy buggy!).

Otherwise, I suggest you run your own header cleanser before trying to parse invalid headers if you don't want the parser to tell you it's invalid.
