### ISSUE TITLE
"invalid parameter format" on trailing semicolon

### ISSUE THREAD

**Issue by TanninOne** [jshttp/content-disposition#19]
So I get a "invalid parameter format" exception with this
`require('content-disposition').parse('attachment; filename="sample.zip";');`
due to the trailing semicolon since the final check in the parse function
` if (index !== -1 && index !== string.length) {`
returns false, index is one less than string.length.

Now I don't know if the trailing semicolon is valid according to the spec but I got this from an actual webserver and browsers apparently don't mind.

**Comment by dougwilson** [comment]
Right now this is expected, because it's invalid according to the specification, because the `;` character is the _start_ of a parameter, and thus a trailing one means an incomplete parameter. I know browsers and others basically have a parsing mode than is more lax, but I don't understand the specific rules they are following. If someone wants to open a new issue / PR with a clear outline of the specific rules their parser uses, we can accept it under a `lax` parsing option.
