### ISSUE TITLE
Many servers return content-disposition with a trailing semicolon.

### ISSUE THREAD

**Issue by danielgindi** [jshttp/content-disposition#8]
Those cause an exception, since the regex does not detect a valid parameter after that semicolon...

They could be removed using `cd.replace(/;$/, '')`

**Comment by dougwilson** [comment]
Thanks for the information! This module purely follows the RFC, though.

You can find information regarding the specification in the references section https://github.com/jshttp/content-disposition/blob/master/README.md#references

The RFC says a trailing semicolon is not valid (and I copied the ABNF you can read into the comments of this module).

I would say to let them know they have buggy headers and you may want to apply that regular expression to responses you know have buggy headers before trying to parse.

**Comment by danielgindi** [comment]
I figured you'd say that, but browsers do "forgive" trailing semicolons and parse the header to supply correct filenames when downloading - so maybe it should be an option.

In any case - the information is here for someone to find it when wanting to know how to avoid those nasty semicolons :-)

**Comment by dougwilson** [comment]
Yea, I know they forgive a lot of things in a lot of ways (though there are various things Firefox has been trying to tighten, since being too forgiving ends up leading to bugs in parsing). Currently this module is primarily used to format a the header (so you can generate actually valid headers; too many people think they can just get away with string concatenation because "it's not that hard") and the parse is being dual-used to parse and validate.

I think if there is some kind of new major version releases that does more forgiving parsing, we need to take a survey of the Internet to determine what is actually the common mistakes in the header values to even understand what we need to parse, otherwise how can we come up with a parser?
